### ISSUE TITLE
Kills Sonar Server

### ISSUE THREAD

**Issue by berenerchamion** [CreditMutuelArkea/sonar-apigee-plugin#1]
Installing this seems to kill our server (Sonar 7.0+). 

ava.lang.IllegalStateException: Fail to load plugin Apigee [apigee]
    at
org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:88)
    at
org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:585)
    at org.sonar.server.platform.Platform.start(Platform.java:211)
    at
org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
    at org.sonar.server.platform.Platform.access$500(Platform.java:46)
    at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
    at
org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
    at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
    at
org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to register extension
com.arkea.satd.sonar.xml.ApigeeXmlRulesDefinition from plugin 'apigee'
    at
org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:241)
    at
org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:125)
    at
org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:80)
    ... 9 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredFields(Class.java:1916)
    at
org.picocontainer.injectors.AdaptingInjection$2.run(AdaptingInjection.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at
org.picocontainer.injectors.AdaptingInjection.injectionFieldAnnotated(AdaptingInjection.java:209)
    at
org.picocontainer.injectors.AdaptingInjection.fieldAnnotatedInjectionAdapter(AdaptingInjection.java:188)
    at
org.picocontainer.injectors.AdaptingInjection.createComponentAdapter(AdaptingInjection.java:57)
    at
org.picocontainer.behaviors.AbstractBehaviorFactory.createComponentAdapter(AbstractBehaviorFactory.java:44)
    at
org.picocontainer.behaviors.OptInCaching.createComponentAdapter(OptInCaching.java:45)
    at
org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:536)
    at
org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
    at
org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
    at
org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:239)
    ... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
    at
org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
    ... 25 common frames omitted

**Comment by ntiss** [comment]
Hi @berenerchamion 

Indeed, you're right. I can reproduce. Thank you for the stacktrace and sorry for the failure.

Here is a quick explaination : the Apigee plugin shares the classloader of sonar-xml-plugin.
But with sonar-xml-plugin 1.5.0+, the team has made some cleaning ([see here](https://github.com/SonarSource/sonar-xml/commit/64a1e1e2a31466f5a4001623742fad4e87f8ab6d#diff-bb20f1dd38c618199bbf46a85542dc34)) and has dropped some depedencies which are now missing.

For the moment, I can propose you these 2 choices : 
- either downgrade to sonar-xml-plugin 1.4.3 (build 1027). The one which comes with a fresh install of SQ 7.0 
- or try this fix [sonar-apigee-plugin-1.2.0-SNAPSHOT.zip](https://github.com/CreditMutuelArkea/sonar-apigee-plugin/files/1865914/sonar-apigee-plugin-1.2.0-SNAPSHOT.zip) while I look for a better solution. Replace the jar in $SONAR_HOME/extensions/plugins/ (I just added the missing deps, the bundle is heavier, it seems still working with old SQ releases : 5.6.7 and 6.7.2.)

Let me know which option you choose and if it works.

Btw, I always appreciate feedback from people using Apigee and this Sonar plugin in their companies. Could you tell me more about your usage (by private mail), please ?

**Comment by berenerchamion** [comment]
I will try it out when I have the time. Thanks for responding - much appreciated.

**Comment by ntiss** [comment]
Hi @berenerchamion 

I've published the 1.2.0-RC1 with a better fix than the SNAPSHOT above.
Please use this one instead : [https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/download/v1.2.0-RC1/sonar-apigee-plugin-1.2.0-RC1.jar](https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/download/v1.2.0-RC1/sonar-apigee-plugin-1.2.0-RC1.jar)

The final release 1.2.0 will be available in the Sonar MarketPlace after the [RFF feedback period](https://groups.google.com/forum/#!topic/sonarqube/bngk8ga4beI) (of course, if everything is ok).

**Comment by ntiss** [comment]
The release 1.2.0 fixes this bug.
It is available in the Sonar Marketplace.
