### ISSUE TITLE
manifest.xml is being see an policy when it is actually not one

### ISSUE THREAD

**Issue by hitjay2002** [CreditMutuelArkea/sonar-apigee-plugin#2]
The Plugin reports Unattached Policy Error for manifest.xml. manifest.xml is an overview of the proxy and that xml won't be attached to any flow though it is part of API proxy artifacts.. So the presence of a manifest.xml shouldn't be reported as unattached as it is not a policy.

The Plugin reports Unattached Policy Error for file.xsl. file.xsl is a file used by XSLT policy and that xml won't be attached to any flow though it is part of API proxy artifacts. So the presence of a file.xsl shouldn't be reported as unattached as it is not a policy.

The Plugin reports Unattached Policy Error for pom.xml. pom.xml is a file with CI steps that will run when the build job is triggered and it won't be attached to any flow though it is part of API proxy artifacts. So the presence of a pom.xml shouldn't be reported as unattached as it is not a policy. This can be easily recreated by adding a pom.xml to the bundle.

It will be really helpful for the users of the Plugin if these can be fixed.

**Comment by ntiss** [comment]
Hi @hitjay2002 

I'll take a look at your problem.
In order to reproduce, could you provide here a bundle apiroxy.zip (without any sensitive data) which presents both of the issues, please ?
And a last question, which version of Apigee are you using ?

Thx.

**Comment by hitjay2002** [comment]
I wouldn't be able to send a bundle. 180423 is the release ID if that is what you are looking for.

**Comment by hitjay2002** [comment]
Yes I can provided there is a jar to import.

**Comment by ntiss** [comment]
Hi @hitjay2002 

FYI, the manifest doesn't exist on Apigee private cloud installation.
And it was tricky for the XSL files. I created the new rule BN502 to treat them.

Please try with this new pre-release : [https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/tag/v1.3.0-RC1](https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/tag/v1.3.0-RC1)  (install sonar-apigee-plugin-1.3.0-RC1.jar)

I'd appreciate your feedback to ensure that everything is ok now.
Then, I'll publish the definitive release in Sonar Marketplace.

**Comment by hitjay2002** [comment]
Thank you. I will update post installation and run.

**Comment by hitjay2002** [comment]
The fix seems to be working. Please release it at your convenience.

**Comment by ntiss** [comment]
Thx for the feedback.
The release process is in progress here : [https://groups.google.com/forum/#!topic/sonarqube/sq4TLQRNjTw](https://groups.google.com/forum/#!topic/sonarqube/sq4TLQRNjTw)
The release 1.3.0 will be available in the Sonar Marketplace next week.

Btw, I always appreciate feedback from people using Apigee and this Sonar plugin in their companies. Could you tell me more about your usage (by private mail to nicolas[dot]tisserand[at]arkea.com), please ?

**Comment by hitjay2002** [comment]
I have sent an e-mail on the usage of this.

**Comment by ntiss** [comment]
Hi @hitjay2002 

FYI, the release 1.3.0 has been validated by SonarSource and is now available in the Marketplace.
Thank you for the feedbacks.
