### ISSUE TITLE
sonar-apigee not compatible with SonarXML 2.0.1

### ISSUE THREAD

**Issue by alexandre-frigout-sonarsource** [CreditMutuelArkea/sonar-apigee-plugin#5]
We dropped the XmlSchemaCheck rule from SOnarXML as of 2.0.1 version ([SONARXML-84](https://jira.sonarsource.com/browse/SONARXML-84))
This plugin is then not compatible with the latest version of SonarXML.

**Comment by ntiss** [comment]
Hi @alexandre-frigout-sonarsource ,
Thanks for this feedback.
I'm aware of this since last week (https://github.com/ntiss/sonar-apigee-plugin/issues/22) . I'll work on a release as soon as possible.
Is there any existing document about how to migrate a plugin like mine ? Or should I work alone ?

**Comment by alexandre-frigout-sonarsource** [comment]
Hi @ntiss,
If you need help developing your plugin you should go to our [community forum ](https://community.sonarsource.com/) and raise your issue. You should get tips to make your plugin compatible with the latest SonarXML.

**Comment by ntiss** [comment]
Hi @alexandre-frigout-sonarsource 
I've published the RC0 for feedback : https://community.sonarsource.com/t/rff-sonar-apigee-plugin-2-0-0/8338
The final release will be available in the marketplace soon after the end of the week.
The new release will be compatible with SonarQube 6.7 to 7.7 with sonar-xml plugin in 2.0.1 version.

**Comment by ntiss** [comment]
Hi @alexandre-frigout-sonarsource 
This issue is now closed. Fix is in the release 2.0.0 : https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/tag/v2.0.0
Available in the SonarQube Marketplace.
Thanks for reporting.
