### ISSUE TITLE
DefaultFaultRule vs FaultRune without condition

### ISSUE THREAD

**Issue by karsten-wagner** [CreditMutuelArkea/sonar-apigee-plugin#9]
I recently noticed the following rule was triggered on my proxy code: `apigee-xml:FaultRuleAndDefaultFaultRuleCheck`
--> "DefaultFaultRule defined and FaultRule without condition"

I agree it's a bad practice to define a fault rule without a condition. However this rule seems to complain explicitly that the use of a default fault rule is pointless if a "regular" fault rule without condition exists...

Here I would recommend to check one level deeper... If the DefaultFaultRule has setting `<AlwaysEnforce>true</AlwaysEnforce>`, then it would still be executed and this "bug" is not needed. There will still be the other rule that will complain about the missing condition on the regular fault rule (`apigee-xml:FaultRuleConditionCheck`)...

**Comment by ntiss** [comment]
Hi @karsten-wagner 
Thank you for point this out. I'll let you know here when an enhancement is available.

**Comment by ntiss** [comment]
Hi @karsten-wagner 

A fix is now available for this issue : 
* Release 2.1.1 if you run SQ 7.9 to 8.7.1
* Release 3.0.0 with SQ 8.8 and later.
